
# use try except block

try:
    no1 = int(input("no1: "))
    no2 = int(input("no2: "))
    print(no1 + no2)

except Exception as a:
    print(a)


